name: reproductor
description: Aplicación reproductor de música

# La siguiente línea define la versión y build number de tu aplicación
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  material_design_icons_flutter: ^5.0.6595 # Iconos adicionales

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ # Opcional para iconos personalizados